# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.pre.zsh"
#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Load shared zsh configs
if [[ -s "${ZDOTDIR:-$HOME}/.config/zprezto/common.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.config/zprezto/common.zsh"
fi

# Load OS specific zsh configs
if [[ -s "${ZDOTDIR:-$HOME}/.config/zprezto/specific.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.config/zprezto/specific.zsh"
fi

# Customize to your needs...
export PATH=${PATH}:$HOME/.local/bin:$HOME/go/bin

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.post.zsh"
